### ISSUE TITLE
Sample code cannot work on Adafruit Feather M0

### ISSUE THREAD

**Issue by adashen** [Azure/azure-iot-arduino-protocol-mqtt#3]
Hi, 
I just tried to run the sample code on Adafruit Feather M0. However, it cannot work. I have installed all the required libraries. And the error in Serial Monitor is:
Error: Time:Fri Jan 20 04:51:17 2017 File:C:\Users\shenwe\Documents\Arduino\libraries\AzureIoTUtility\src\adapters\tlsio_arduino.c Func:tlsio_arduino_open Line:264 TLS failed to start the connection process.
Error: Time:Fri Jan 20 04:51:17 2017 File:C:\Users\shenwe\Documents\Arduino\libraries\AzureIoTProtocol_MQTT\src\azure_umqtt_c\mqtt_client.c Func:mqtt_client_connect Line:884 Error: io_open failed

And after adding more log. The socket error is -12, SOCK_ERR_CONN_ABORTED.

**Comment by Eskibear** [comment]
Exactly same error messages, and [here](https://github.com/Azure-Samples/iot-hub-c-m0wifi-getstartedkit/issues/44#issuecomment-274020457) are some details.

**Comment by Eskibear** [comment]
More details found.

Currently:
- M0 **successfully** connects *.azure-devices.net:**443** via TLS v1.2
- M0 **fails to** connect *.azure-devices.net:**8883** via TLS v1.2

After using tcpdump/wireshark, we notice that both use  `Cipher Suite: TLS_RSA_WITH_AES_128_GCM_SHA256 (0x009c)`, 
but have differences in connection establishment:
- port 443
```
C->S: Client Hello
S->C: Server Hello, Certificate, Server Hello Done
C->S: Client Key Exchange, Change Cipher Spec, Hello Request, Hello Request
S->C: Change Cipher Spec, Hello Request, Hello Request
Application Data
...
```
- port 8883
```
C->S: Client Hello
S->C: Server Hello, Certificate, **Certificate Request**, Server Hello Done
C->S: Client Key Exchange, Change Cipher Spec, Hello Request, Hello Request
Timeout
```

According to [RFC 5246](https://tools.ietf.org/html/rfc5246),"_After a certificate_request, if no certificates are available, clients now MUST send an empty certificate list._"
For example:
```
TLSv1.2 Record Layer: Handshake Protocol: Certificate
    Content Type: Handshake (22)
    Version: TLS 1.2 (0x0303)
    Length: 7
    Handshake Protocol: Certificate
        Handshake Type: Certificate (11)
        Length: 3
        Certificates Length: 0
HEX value: 16 03 03 00 07 0b 00 00  03 00 00 00
```

Here's another tcpdump log when I successfully establish the connection using directly  `openssl s_client -connect t-yazh-iothub.azure-devices.net:8883` in my own PC. Because my PC supports more cipher suites, it use `Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (0xc028)` after negotiation.
```
C->S: Client Hello
S->C: Server Hello, Certificate, Server Key Exchange, **Certificate Request**, Server Hello Done
C->S: **Certificate**, Client Key Exchange, Change Cipher Spec, Encrypted Handshake Message
S->C: Change Cipher Spec, Encrypted Handshake Message
Connected.
```
So azure service in 8883 port sends a Certificate Request, but the client doesn't even respond it with an empty certificate list in the packet. I think that is probably the reason that blocks the connection establishment.

@mamokarz Could you help take a look?

PS:
We tried both `WiFi101` and `Adafruit_WINC1500` libraries, and get the same result.

**Comment by gmhewett** [comment]
I am having the same issues. Is there any update on this?

**Comment by adashen** [comment]
@gmhewett it seems currently mqtt cannot work on feather M0. Our work around is using https protocol.

**Comment by gmhewett** [comment]
@adashen it seems you are correct. HTTP works for me as well; however, I need to be able to send commands to the device rather frequently, and the SDK currently only supports polling the IoT Hub every 25 minutes or so, as per HTTP guidelines. Info here if interested [https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messaging#cloud-to-device-messages](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messaging#cloud-to-device-messages).

**Comment by Eskibear** [comment]
@gmhewett Currently we have 2 devices polling iothub every 1s simultaneously, and they work well. There is about 2-3s delay between sending & receiving the C2D message. Maybe the 25min is for performance concern in production enviroment, I don't know where the number "25min" come from.

**Comment by Eskibear** [comment]
It's resolved by [this new firmware](https://github.com/arduino/Arduino/pull/6069#issuecomment-286223342)

**Comment by gmhewett** [comment]
@Eskibear thanks for referencing this! Did you use the firmware updater to update just the SSL certificates, or did you update the entire WINC1500 firmware? Any tips on updating?

EDIT: For those needing to update, here is what I did that worked.

1. Update the Arduinio IDE to the newest hourly build from [here](https://www.arduino.cc/en/Main/Software).
2. Open the WiFi101 -> FirmwareUpdater example.
3. Add the following defines (not sure if completely necessary, but was partially following [this](http://arduino.stackexchange.com/questions/32196/adafruit-feather-m0-wifi-firmware-update)):
```
#define WINC_CS 8
#define WINC_IRQ 7
#define WINC_RST 4
#define WINC_EN 2 
```
4. Add the following in the setup() function:
`WiFi.setPins(8,7,4,2); `
5. Upload the sketch.
6. Open Tools -> WiFi101 Firmware Updater.
7. Check the connection and make sure it's all good.
8. If you have a WINC1500 model B (see last character on first line of chip text), upload the newest firmware while the sketch is running on the device.

**Comment by Eskibear** [comment]
@gmhewett update the firmware.  You may refer to [this](https://github.com/arduino-libraries/WiFi101-FirmwareUpdater-Plugin).

**Comment by adashen** [comment]
Verified and the issue has been solved
